- name: Ensure cifs-utils is installed
  ansible.builtin.package:
    name: cifs-utils
    state: present

- name: Copy over smb credentials
  ansible.builtin.copy:
    src: files/.smbcredentials
    dest: /root/.smbcredentials
    owner: root
    group: root
    mode: '0700'
  no_log: true

- name: Mount shared drive and add to fstab
  ansible.posix.mount:
    src: //10.59.20.3/main  # Replace with the actual device name or UUID of your shared drive
    path: /mnt/main # Replace with the desired mount point
    fstype: cifs # Replace with the file system type
    opts: "credentials=/root/.smbcredentials,iocharset=utf8,file_mode=0777,dir_mode=0777"
    state: mounted
