- name: Run Watchtower container with notifications
  community.docker.docker_container:
    name: watchtower
    image: containrrr/watchtower
    state: started
    restart_policy: unless-stopped
    detach: true
    pull: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env:
      WATCHTOWER_NOTIFICATION_URL: "discord://{{ DISCORD_CHANNEL_ID_TOKEN }}"
