---
ansible-navigator:
  ansible:
    inventory:
      entries:
        - inventory.ini

  logging:
    level: critical
  playbook-artifact:
    enable: False
    replay: /tmp/test_artifact.json
    save-as: /tmp/test_artifact.json
  time-zone: America/New_York
