[client-machines]
rtxserver
RTX-Greed ansible_port=22590
x1-carbon

[general]
prince
tavern
overflow

[master_node]
Shadow-Knight
Shadow-Warrior
Shadow-Paladin

[worker_node]
Shadow-Barbarian

[k8s:children]
master_node
worker_node

[ubuntu:children]
general
k8s

[ubuntu:vars]
ansible_become_exe=/usr/bin/sudo.ws

[jumpbox]
RTX-Greed ansible_port=22590
overflow

[proxmox:children]
general
k8s
