[general]
rtxserver

[general-vm]
prince
data
overflow

[master_node]
sensei[1:3]

[worker_node]
surf[1:3]

[k8s:children]
master_node
worker_node

[ubuntu:children]
general
general-vm
k8s

[xcp_ng:children]
general-vm
k8s
