# Initial Wave of Configuration

- hosts: all
  roles:
    - role: base
      become: true
      tags: base
    - role: certificates
      become: true
      tags: certificates
    - role: auto_reboot
      become: true
      tags: auto_reboot

- hosts: proxmox
  roles:
    - role: proxmox
      become: true
      tags: proxmox

- hosts: general, client-machines
  roles:
    - role: docker
      become: true
      tags: docker
    

- hosts: storage, general, client-machines
  roles:
    - role: sharedrive
      become: true
      tags: sharedrive

- hosts: storage
  roles:
    - role: smb-server
      tags: smb-server

# Dependant Configurations

- hosts: master_node
  roles:
    - role: k3s_master
      become: true
      tags: k3s_master

- hosts: worker_node
  roles:
    - role: k3s_worker
      become: true
      tags: k3s_worker

# Host Specific Configurations

- hosts: prince
  roles:
    - role: prince
      become: true
      tags: prince
    # - role: obsidian
    #   tags: obsidian
    - role: n8n
      tags: n8n

- hosts: tavern
  roles:
    - role: data
      become: true
      tags: data

- hosts: overflow
  roles:
    - role: jumpbox
      become: true
      tags: jumpbox

- hosts: rtxserver
  roles:
    - role: rtxserver
      tags: rtxserver
